version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    environment:
    - NGINX_HOST=192.168.99.100
    - NGINX_PORT=80
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules #Se indica que no se sobreescriba este directorio
      - ./server:/usr/app #Copia todo lo que está en server a /app (dentro del contenedor, para que no esté en la raiz), excepto node_modules
    environment: # Establecemos las variables de entorno de la aplicación
      #Estos valores los consultamos de dockerhub
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app